# Generated by Django 5.2.3 on 2025-09-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='cost',
            new_name='fare',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner',
            new_name='driver',
        ),
        migrations.AddField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.CreateModel(
            name='OBDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('fuel_level', models.FloatField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obd_records', to='core.vehicle')),
            ],
        ),
    ]
