# Generated by Django 5.2.3 on 2025-09-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cost_ride_fare_rename_owner_vehicle_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
