# Generated by Django 5.2.6 on 2025-09-08 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_university_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='liability_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='liability_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VehicleAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', models.CharField(max_length=200)),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('liability_accepted', models.BooleanField(default=False)),
                ('liability_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('availability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='core.vehicleavailability')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
